//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickAnalyzer {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class QuickAnalyzerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static QuickAnalyzerSettings defaultInstance = ((QuickAnalyzerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new QuickAnalyzerSettings())));
        
        public static QuickAnalyzerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string thuMucDich {
            get {
                return ((string)(this["thuMucDich"]));
            }
            set {
                this["thuMucDich"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string thuMucNguon {
            get {
                return ((string)(this["thuMucNguon"]));
            }
            set {
                this["thuMucNguon"] = value;
            }
        }
    }
}
