//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickTranslator
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class PostTTVFormSettings : global::System.Configuration.ApplicationSettingsBase
    {

        private static PostTTVFormSettings defaultInstance = ((PostTTVFormSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PostTTVFormSettings())));

        public static PostTTVFormSettings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string discussionUrl {
            get {
                return ((string)(this["discussionUrl"]));
            }
            set {
                this["discussionUrl"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string line1 {
            get {
                return ((string)(this["line1"]));
            }
            set {
                this["line1"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string line2 {
            get {
                return ((string)(this["line2"]));
            }
            set {
                this["line2"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string line3 {
            get {
                return ((string)(this["line3"]));
            }
            set {
                this["line3"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string line4 {
            get {
                return ((string)(this["line4"]));
            }
            set {
                this["line4"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool spoilerHanViet {
            get {
                return ((bool)(this["spoilerHanViet"]));
            }
            set {
                this["spoilerHanViet"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool spoilerTrung {
            get {
                return ((bool)(this["spoilerTrung"]));
            }
            set {
                this["spoilerTrung"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool spoilerViet {
            get {
                return ((bool)(this["spoilerViet"]));
            }
            set {
                this["spoilerViet"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool spoilerVietPhraseOneMeaning {
            get {
                return ((bool)(this["spoilerVietPhraseOneMeaning"]));
            }
            set {
                this["spoilerVietPhraseOneMeaning"] = value;
            }
        }
    }
}
