//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtendedWebBrowser2.Properties
{
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        [System.Configuration.UserScopedSettingAttribute()]
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowScriptErrors {
            get {
                return ((bool)(this["ShowScriptErrors"]));
            }
            set {
                this["ShowScriptErrors"] = value;
            }
        }

        [System.Configuration.UserScopedSettingAttribute()]
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.Configuration.DefaultSettingValueAttribute("Medium")]
        public ExtendedWebBrowser2.PopupBlockerFilterLevel FilterLevel {
            get {
                return ((ExtendedWebBrowser2.PopupBlockerFilterLevel)(this["FilterLevel"]));
            }
            set {
                this["FilterLevel"] = value;
            }
        }

        [System.Configuration.UserScopedSettingAttribute()]
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.Configuration.DefaultSettingValueAttribute("1")]
        public string VietPhraseWrapType {
            get {
                return ((string)(this["VietPhraseWrapType"]));
            }
            set {
                this["VietPhraseWrapType"] = value;
            }
        }

        [System.Configuration.UserScopedSettingAttribute()]
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.Configuration.DefaultSettingValueAttribute("0")]
        public string VietPhraseOneMeaningWrapType {
            get {
                return ((string)(this["VietPhraseOneMeaningWrapType"]));
            }
            set {
                this["VietPhraseOneMeaningWrapType"] = value;
            }
        }

        [System.Configuration.UserScopedSettingAttribute()]
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.Configuration.DefaultSettingValueAttribute("1")]
        public string BlockImages {
            get {
                return ((string)(this["BlockImages"]));
            }
            set {
                this["BlockImages"] = value;
            }
        }

        [System.Configuration.UserScopedSettingAttribute()]
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.Configuration.DefaultSettingValueAttribute("1")]
        public string BlockFlashes {
            get {
                return ((string)(this["BlockFlashes"]));
            }
            set {
                this["BlockFlashes"] = value;
            }
        }

        [System.Configuration.UserScopedSettingAttribute()]
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.Configuration.DefaultSettingValueAttribute("Không dịch")]
        public string TranslationMode {
            get {
                return ((string)(this["TranslationMode"]));
            }
            set {
                this["TranslationMode"] = value;
            }
        }

        [System.Configuration.UserScopedSettingAttribute()]
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.Configuration.DefaultSettingValueAttribute("100%")]
        public string Zoom {
            get {
                return ((string)(this["Zoom"]));
            }
            set {
                this["Zoom"] = value;
            }
        }

        [System.Configuration.UserScopedSettingAttribute()]
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.Configuration.DefaultSettingValueAttribute("Original Size")]
        public string TextSize {
            get {
                return ((string)(this["TextSize"]));
            }
            set {
                this["TextSize"] = value;
            }
        }

        [System.Configuration.UserScopedSettingAttribute()]
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.Configuration.DefaultSettingValueAttribute("Times New Roman")]
        public string Font {
            get {
                return ((string)(this["Font"]));
            }
            set {
                this["Font"] = value;
            }
        }

        [System.Configuration.UserScopedSettingAttribute()]
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.Configuration.DefaultSettingValueAttribute("0")]
        public int TranslationAlgorithm {
            get {
                return ((int)(this["TranslationAlgorithm"]));
            }
            set {
                this["TranslationAlgorithm"] = value;
            }
        }

        [System.Configuration.UserScopedSettingAttribute()]
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.Configuration.DefaultSettingValueAttribute("1")]
        public int PrioritizedName {
            get {
                return ((int)(this["PrioritizedName"]));
            }
            set {
                this["PrioritizedName"] = value;
            }
        }
    }
}
