using System;

namespace ExtendedWebBrowser2
{
    internal static class NativeMethods
    {
        public enum OLECMDF
        {
            OLECMDF_DEFHIDEONCTXTMENU = 32,
            OLECMDF_ENABLED = 2,
            OLECMDF_INVISIBLE = 16,
            OLECMDF_LATCHED = 4,
            OLECMDF_NINCHED = 8,
            OLECMDF_SUPPORTED = 1
        }

        public enum OLECMDID
        {
            OLECMDID_OPEN = 1,
            OLECMDID_NEW,
            OLECMDID_SAVE,
            OLECMDID_SAVEAS,
            OLECMDID_SAVECOPYAS,
            OLECMDID_PRINT,
            OLECMDID_PRINTPREVIEW,
            OLECMDID_PAGESETUP,
            OLECMDID_SPELL,
            OLECMDID_PROPERTIES,
            OLECMDID_CUT,
            OLECMDID_COPY,
            OLECMDID_PASTE,
            OLECMDID_PASTESPECIAL,
            OLECMDID_UNDO,
            OLECMDID_REDO,
            OLECMDID_SELECTALL,
            OLECMDID_CLEARSELECTION,
            OLECMDID_ZOOM,
            OLECMDID_GETZOOMRANGE,
            OLECMDID_UPDATECOMMANDS,
            OLECMDID_REFRESH,
            OLECMDID_STOP,
            OLECMDID_HIDETOOLBARS,
            OLECMDID_SETPROGRESSMAX,
            OLECMDID_SETPROGRESSPOS,
            OLECMDID_SETPROGRESSTEXT,
            OLECMDID_SETTITLE,
            OLECMDID_SETDOWNLOADSTATE,
            OLECMDID_STOPDOWNLOAD,
            OLECMDID_FIND = 32,
            OLECMDID_DELETE,
            OLECMDID_PRINT2 = 49,
            OLECMDID_PRINTPREVIEW2,
            OLECMDID_PAGEACTIONBLOCKED = 55,
            OLECMDID_PAGEACTIONUIQUERY,
            OLECMDID_FOCUSVIEWCONTROLS,
            OLECMDID_FOCUSVIEWCONTROLSQUERY,
            OLECMDID_SHOWPAGEACTIONMENU,
            OLECMDID_ADDTRAVELENTRY,
            OLECMDID_UPDATETRAVELENTRY,
            OLECMDID_UPDATEBACKFORWARDSTATE,
            OLECMDID_OPTICAL_ZOOM,
            OLECMDID_OPTICAL_GETZOOMRANGE,
            OLECMDID_WINDOWSTATECHANGED,
            OLECMDID_ACTIVEXINSTALLSCOPE,
            OLECMDID_UPDATETRAVELENTRY_DATARECOVERY
        }

        public enum OLECMDEXECOPT
        {
            OLECMDEXECOPT_DODEFAULT,
            OLECMDEXECOPT_DONTPROMPTUSER = 2,
            OLECMDEXECOPT_PROMPTUSER = 1,
            OLECMDEXECOPT_SHOWHELP = 3
        }
    }
}
